# Generated by Django 2.1 on 2018-08-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
