# Generated by Django 2.1 on 2018-08-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='debt_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
